name: apply-all

on:
  workflow_dispatch:
    inputs:
      input_environment:
        description: 'Input environment'
        required: true 
        type: choice
        options:
        - dev
        - stag
        - prod

jobs:
  network:
    uses: bombsdontbite/multi-environment-infrastructure-provisioning/.github/workflows/terraform-stack.yml@main
    with:
      input_environment: ${{ inputs.input_environment }}
      input_stack: vpc
      input_mode: apply
    secrets: inherit
  ec2:
    uses: bombsdontbite/multi-environment-infrastructure-provisioning/.github/workflows/terraform-stack.yml@main
    with:
      input_environment: ${{ inputs.input_environment }}
      input_stack: ec2
      input_mode: apply
    secrets: inherit
    needs: network
